services:
  postgres:
    image: "postgres:latest"
    volumes:
      - azure-dev-vm-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "primary"
      POSTGRES_PASSWORD: "primary"
      POSTGRES_DB: "primary"
    ports:
      - "12000:5432"
  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "12001:8080"
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_USERNAME: "primary"
      QUARKUS_DATASOURCE_PASSWORD: "primary"
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/primary"
      AZURE_TENANT_ID: "CHANGE HERE"
      AZURE_CLIENT_ID: "CHANGE HERE"
      AZURE_CLIENT_SECRET: "CHANGE HERE"
      AZURE_SUBSCRIPTION_ID: "CHANGE HERE"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - backend
    ports:
      - "12002:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:12001"
volumes:
  azure-dev-vm-postgres-data: